- src/shipping/delivery/Fabrikam.DroneDelivery.DeliveryService/Services/Constants.cs
- src/shipping/delivery/Fabrikam.DroneDelivery.DeliveryService/Startup.cs
to adress https://github.com/mspnp/microservices-reference-implementation/issues/95
> revert remove dup config for RedisCache

- src/shipping/ingestion/Dockerfilemaven
> Update Maven version to 3.5.4

- deployment.md
Changes instructions to use AKS instead of ACS. These changes involve:
* Replace provisioning of the ACS cluster with equivalent AKS instructions.
* Grant Reader permission for the cluster on the ACR instance
* Grant permission on the linkerd service accounts to query the k8s cluster
In addition to this, the PR includes
* Added bash instruction to open a browser on the Swagger app
* Fixed a typo on "Fluend"
> update instructions to deploy the RI to AKS instead of ACS

- deployment.md
- Remove unused SSH_PRIVATE_KEY_FILE variable
- Add PROJECT_ROOT when needed
- Add change-cause annotation to Helm deployments
> Minor fixes to deployment instructions

- deployment.md
If default is table, this does not work.
> Explicitly set output to json

- azuredeploy.json
- deployment.md
- deploymentCICD.md
- src/shipping/delivery/Dockerfile
- src/shipping/delivery/Fabrikam.DroneDelivery.Common/Fabrikam.DroneDelivery.Common.csproj
- src/shipping/delivery/Fabrikam.DroneDelivery.Common/Location.cs
- src/shipping/delivery/Fabrikam.DroneDelivery.Common/UserAccount.cs
- src/shipping/delivery/Fabrikam.DroneDelivery.DeliveryService.Tests/DeliveriesControllerRoutingFixture.cs
- src/shipping/delivery/Fabrikam.DroneDelivery.DeliveryService.Tests/Fabrikam.DroneDelivery.DeliveryService.Tests.csproj
- src/shipping/delivery/Fabrikam.DroneDelivery.DeliveryService.Tests/GlobalLoggerMiddlewareFixture.cs
- src/shipping/delivery/Fabrikam.DroneDelivery.DeliveryService/Controllers/DeliveriesController.cs
- src/shipping/delivery/Fabrikam.DroneDelivery.DeliveryService/Fabrikam.DroneDelivery.DeliveryService.csproj
- src/shipping/delivery/Fabrikam.DroneDelivery.DeliveryService/Models/Delivery.cs
- src/shipping/delivery/Fabrikam.DroneDelivery.DeliveryService/Program.cs
- src/shipping/delivery/Fabrikam.DroneDelivery.DeliveryService/Startup.cs
- src/shipping/dronescheduler/Dockerfile
- src/shipping/dronescheduler/Fabrikam.DroneDelivery.DroneSchedulerService.BulkImport/Fabrikam.DroneDelivery.DroneSchedulerService.BulkImport/Fabrikam.DroneDelivery.DroneSchedulerService.BulkImport.csproj
- src/shipping/dronescheduler/Fabrikam.DroneDelivery.DroneSchedulerService.Tests/CustomWebApplicationFactory.cs
- src/shipping/dronescheduler/Fabrikam.DroneDelivery.DroneSchedulerService.Tests/Fabrikam.DroneDelivery.DroneSchedulerService.Tests.csproj
- src/shipping/dronescheduler/Fabrikam.DroneDelivery.DroneSchedulerService/Controllers/DroneDeliveriesController.cs
- src/shipping/dronescheduler/Fabrikam.DroneDelivery.DroneSchedulerService/Fabrikam.DroneDelivery.DroneSchedulerService.csproj
- src/shipping/dronescheduler/Fabrikam.DroneDelivery.DroneSchedulerService/Program.cs
- src/shipping/dronescheduler/Fabrikam.DroneDelivery.DroneSchedulerService/Startup.cs
- src/shipping/workflow/Dockerfile
- src/shipping/workflow/Fabrikam.Workflow.Service.Tests/DeliveryServiceCallerIntegrationTests.cs
- src/shipping/workflow/Fabrikam.Workflow.Service.Tests/DroneSchedulerServiceCallerIntegrationTests.cs
- src/shipping/workflow/Fabrikam.Workflow.Service.Tests/Fabrikam.Workflow.Service.Tests.csproj
- src/shipping/workflow/Fabrikam.Workflow.Service.Tests/PackageServiceCallerIntegrationTests.cs
- src/shipping/workflow/Fabrikam.Workflow.Service.Tests/RequestProcessorIntegrationTests.cs
- src/shipping/workflow/Fabrikam.Workflow.Service/Fabrikam.Workflow.Service.csproj
* delivery app upgraded to ASP.NET Core 3.1
* dronescheduler app upgraded to ASP.NET Core 3.1
* workflow app upgraded to NET Core 3.1
> Drone Delivery 0.1.0 (basic) - upgrade to .NET Core 3.1

- deployment.md
add a note to the deployment steps indicating required permissions
> required permissions note

- README.md
add links to articles that are great companion of this Microservices Reference Implementation
> add more links to our docs

- deployment.md
- deploymentCICD.md
include CA message warning users about using self-signed certificates
closes: #190580
> add CA warning message

- deployment.md
- deploymentCICD.md
- add CA message warning users about using self-signed certificates
- catch up with master for minor improvements/bug fixes
- fixing the testing section so that it works
- required permissions note
> add ca warning note for basic + catchup minor fixes in master

- deployment.md
based on @PageWriter-MSFT review 👍 , we bug fix the helm usage for add-pod-identity chart
`helm install [NAME] [CHART]`
> fix helm usage for add-pod-idenitty

- charts/ingestion/templates/ingestion-secret-ingress-queue.yaml
- charts/package/templates/package-secrets.yaml
> [adv] change secrets to required in ingestion and package 

- deployment.md
- deploymentCICD.md
> [adv] add suffix to the deployment names

- charts/delivery/templates/delivery-identity.yaml
- charts/dronescheduler/templates/dronescheduler-identity.yaml
- charts/workflow/templates/workflow-identity.yaml
For more information, https://github.com/Azure/aad-pod-identity#v160-breaking-change
> [adv] adapt Azure Identities objects to aad-pod-identity 1.6.0 breaking change

- deployment.md
- deploymentCICD.md
For more information,
- https://github.com/Azure/aad-pod-identity#v160-breaking-change
- https://github.com/Azure/application-gateway-kubernetes-ingress/pull/825
> [adv] adapt AGIC to aad-pod-identity 1.6.0 breaking change

- charts/ingestion/templates/ingestion-secret-ingress-queue.yaml
- charts/package/templates/package-secrets.yaml
> [basic] change secrets to required in ingestion and package

- deployment.md
- deploymentCICD.md
> [basic] add suffix to the deployment names

- charts/delivery/templates/delivery-identity.yaml
- charts/dronescheduler/templates/dronescheduler-identity.yaml
- charts/workflow/templates/workflow-identity.yaml
For more information, https://github.com/Azure/aad-pod-identity#v160-breaking-change
> [basic] adapt Azure Identities objects to aad-pod-identity 1.6.0 breaking change

- deployment.md
> Get Helm 2.14.2 properly installed

- README.md
awaiting for https://github.com/mspnp/aks-fabrikam-dronedelivery/pull/2
- communicate our intent, and recommend what should be the ideal path to follow.
> Update basic readme

- deployment.md
- deploymentCICD.md
add call out around public registries specially for NGINX which is the only public one at the moment.
> Add message around public registries

- azuredeploy.json
- scripts/setup/install-drone-demo.sh
Reverts mspnp/microservices-reference-implementation#198
> Revert "Russ/update deploy retry"

- azuredeploy.json
- deployment.md
Fixes https://github.com/mspnp/microservices-reference-implementation/issues/203.
I've also updated a few AZ CLI commands to the most up to date format.
@doodlemania2 / @ferantivero / @ckittel
> Fixed multiple deployment issues

- deployment.md
Fixes https://github.com/mspnp/microservices-reference-implementation/issues/205.
@doodlemania2 / @ferantivero
> bump helm version > 2.17.0

- deployment.md
Fixes https://github.com/mspnp/microservices-reference-implementation/issues/208
- Removes instruction to checkout the basic branch
- Updated and simplified pathing concerns
- Add ACR build for container image creation and push
- Several minor updates / simplifications
@ferantivero / @doodlemania2 
Cc: @ckittel
> Fix branch / path issue + add ACR build and a few other simplification items

- deployment.md
DEPLOYMENT_SUFFIX was  used by not defined
AAD pod identity was not fund on the helm repo, I added instructions to be sure that it was there
> Fixing deploy instructions

- azuredeploy-prereqs.json
- azuredeploy.json
- deployment.md
- k8s/k8s-rbac-ai.yaml
- src/shipping/.dockerignore
- src/shipping/delivery/.dockerignore
- src/shipping/dronescheduler/.dockerignore
- src/shipping/workflow/.dockerignore
-ARM template apis
-Dockerignore to avoid build errors
-A deprecated k8s api version
- Small imrovement on deployment.md
> Refresh-Step1

- azuredeploy.json
- scripts/setup/install-drone-demo.sh
- scripts/setup/windows-setup-container.ps1
A few things have changed in the deployment - these should get updated to avoid failures.
> Fixes to basic valorem demo setup

- deployment.md
- inner-loop-scripts/shell/install-drone-demo.sh
No functional changes, also didn't change the use of deprecated AAD Pod Identity
> Azure AD -> Entra rebranding

- azuredeploy.bicep
based on: https://github.com/mspnp/microservices-reference-implementation/pull/235#discussion_r1452634170
> Adding user node pool

- azuredeploy.bicep
Based on https://github.com/mspnp/microservices-reference-implementation/pull/235#discussion_r1452631962
> Move to User Assigned Identity

- charts/dronescheduler/templates/dronescheduler-deploy.yaml
- charts/workflow/templates/workflow-deploy.yaml
- charts/workflow/templates/workflow-secret-provider.yaml
- charts/workflow/templates/workflow-secret-queue-tls.yaml
- deployment.md
Moving certain non sensible values from the key vault to secrets.
> Update to use latest Fabrikam main branch commit

- deployment.md
Fix heavy exclamation mark broken in deployment.md
> Fix heavy exclamation mark broken in deployment.md

- charts/ingestion/templates/ingestion-deploy.yaml
Fixes #243 
respect successThreshold for livenessProbe and readinessProbe
> fix: successThreshold for livenessProbe and readinessProbe not being respect
